# FOR SIGNUP
POST http://localhost:3000/api/signup
Accept: application/json
Content-Type: application/json

{
 "email": "sahilw@2hospital.com",
 "password": "123",
 "type": "hospital",
 "hospital_placeid":"ChIsJb_iYL-4RdkgRfILoKI4ebYM"
}

###
# FOR SIGNIN
POST http://localhost:3000/api/signin
Accept: application/json
Content-Type: application/json

{
 "email": "sahil@hospital.com",
 "password": "123"
}

###
# NOT NEEDED 
POST http://localhost:3000/api/nearestHospital
Accept: application/json
Content-Type: application/json

{
 "loc_lat":  18.6061181,
 "loc_lng": 73.8066048
}

###
# GET REQUEST
POST http://localhost:3000/api/generate-requests
Accept: application/json
Content-Type: application/json

{
 "loc_lat":  18.6061181,
 "loc_lng": 73.8066048
}