### GET dev_id | For device identification
POST http://localhost:3000/

### ~~~~SIGNUP~~~~
### FOR [HOSPITAL]
POST http://localhost:3000/api/signup
Accept: application/json
Content-Type: application/json

{
 "email": "sahil@hospital.com",
 "password": "123",
 "type": "hospital",
 "hospital_address":"Lotus Multispeciality Hospital, Pimple Saudagar, Pune"
}

### FOR [DRIVER]
POST http://localhost:3000/api/signup
Accept: application/json
Content-Type: application/json

{
 "email": "shruti@driver.com",
 "password": "123",
 "type": "driver",
 "hospital_address":"Lotus Multispeciality Hospital, Pimple Saudagar, Pune",
 "driver_name": "Shruti Shahane", 
 "phone" : "9325827763"
}
### ~~~~~ SIGN UP END ~~~~~~



### ~~~~ SIGNIN ~~~~~
# FOR [HOSPITAL & DRIVER]
POST http://localhost:3000/api/signin
Accept: application/json
Content-Type: application/json

{
 "email": "vaidehi@driver.com",
 "password": "123"
}

### ~~~~ SIGNIN END ~~~~~~

###
# [CLIENT] GET REQUEST
POST http://localhost:3000/api/generate-requests
Accept: application/json
Content-Type: application/json
Cookie: dev_id=3AQEUlBW30

{
 "loc_lat": 18.6061181,
 "loc_lng": 73.8066048
}

###
# [CLIENT] GET STATUS REQUEST BY DEVICE ID  
POST https://localhost:8080/api/check-request-status
Cookie: dev_id=3AQEUlBW30;
###
# [SIGN IN REQUIRED] [HOSPITAL] GET LIST OF REQUEST MADE TO THAT PARTICULAR HOSPITAL
POST http://localhost:3000/api/admin/get_request_list
Accept: application/json
Content-Type: application/json
Cookie: tkn=eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTY0ODgzMjk3Nn0.M8sn4v-A9MJWpGqC5qhw7qf6skclaTPAnLgIWmw34rrzvVcT-vCbrqhxvxJStpJm;


### [HOSPITAL] APPROVE A PATIENT'S / REQUESTOR's REQUEST
POST http://localhost:3000/api/admin/approve_request
Accept: application/json
Content-Type: application/json
Cookie: tkn=eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsImlhdCI6MTY0ODgzMjk3Nn0.M8sn4v-A9MJWpGqC5qhw7qf6skclaTPAnLgIWmw34rrzvVcT-vCbrqhxvxJStpJm;

{
 "req_id" : 1,
 "dev_id" : "3AQEUlBW30"
}


### GET DRIVER's ALLOCATED REQUEST ID
POST http://localhost:3000/api/admin/update-location
Cookie: tkn=eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjMsImlhdCI6MTY0OTA5MDI4Nn0.az-S317J5_d6nRmDA9uPwtaphEwfno4Sl76h10rcCNHHwl8ghVnaL3BhJP2ZaLIM;


### [DRIVER] UPDATE DRIVER'S LOCATION
POST http://localhost:3000/api/admin/update-location/1
Accept: application/json
Content-Type: application/json
Cookie: tkn=eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjIsImlhdCI6MTY0ODg2ODU0MH0.FQfJ-yEfBHwVtAPKsySX_7KymdcQpYGtrxeRnruuLrkEXh-uN25WdTI6zhCLQO3l;

{
 "loc_lat" : 18.00012002,
 "loc_lng": 75.212312
}

### [GET HOSPITAL DETAILS OF A REQUEST]
POST http://localhost:3000/api/get-hospital-details
Cookie: dev_id=3AQEUlBW30;


### [GET PATIENT DETAILS OF A REQUEST]
POST http://localhost:3000/api/get-patient-details
Cookie: dev_id=3AQEUlBW30;


### [GET STATUS DETAILS OF A REQUEST]
POST http://localhost:3000/api/get-status-details
Cookie: dev_id=3AQEUlBW30;


### [GET DRIVER DETAILS OF A REQUEST]
POST http://localhost:3000/api/get-driver-details
Cookie: dev_id=3AQEUlBW30;